#!/usr/bin/env bash
set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── OS Detection ────────────────────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"
info "Detected OS: ${OS} / Arch: ${ARCH}"

# ── Docker check ────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  warn "Docker not found. Installing..."
  case "${OS}" in
    Linux)
      curl -fsSL https://get.docker.com | sh -
      sudo usermod -aG docker "$USER" || true
      ;;
    Darwin)
      error "Please install Docker Desktop for Mac from https://www.docker.com/products/docker-desktop/ then re-run this script."
      ;;
    *)
      error "Unsupported OS: ${OS}. Please install Docker manually."
      ;;
  esac
fi

docker compose version &>/dev/null || error "Docker Compose v2 not found. Update Docker."

# ── Collect user input ───────────────────────────────────────────────────────
read -rp "Enter your domain (e.g. plane.yourdomain.com): " PLANE_DOMAIN
[[ -z "${PLANE_DOMAIN}" ]] && error "Domain cannot be empty."

read -rp "Enter SMTP host (e.g. smtp.sendgrid.net): " EMAIL_HOST
read -rp "Enter SMTP port [587]: " EMAIL_PORT
EMAIL_PORT="${EMAIL_PORT:-587}"
read -rp "Enter SMTP user (your email address): " EMAIL_HOST_USER
read -rsp "Enter SMTP password: " EMAIL_HOST_PASSWORD
echo
read -rp "Enter from address [noreply@${PLANE_DOMAIN}]: " DEFAULT_FROM_EMAIL
DEFAULT_FROM_EMAIL="${DEFAULT_FROM_EMAIL:-noreply@${PLANE_DOMAIN}}"

# ── Generate secrets ─────────────────────────────────────────────────────────
gen_secret() { tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$1"; }
SECRET_KEY=$(gen_secret 50)
PGPASSWORD=$(gen_secret 32)
MINIO_ROOT_PASSWORD=$(gen_secret 32)
RABBITMQ_DEFAULT_PASS=$(gen_secret 32)

# ── Write .env ───────────────────────────────────────────────────────────────
cat > .env <<EOF
# Generated by install.sh on $(date)
PLANE_DOMAIN=${PLANE_DOMAIN}
SECRET_KEY=${SECRET_KEY}
WEB_URL=https://${PLANE_DOMAIN}

PGHOST=plane-db
PGPORT=5432
PGDATABASE=plane
PGUSER=plane
PGPASSWORD=${PGPASSWORD}

REDIS_HOST=plane-redis
REDIS_PORT=6379

RABBITMQ_HOST=plane-rabbitmq
RABBITMQ_PORT=5672
RABBITMQ_DEFAULT_USER=plane
RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

MINIO_ROOT_USER=plane-minio
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_BUCKET_NAME=uploads
AWS_S3_ENDPOINT_URL=http://plane-minio:9000
AWS_ACCESS_KEY_ID=plane-minio
AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
AWS_S3_BUCKET_NAME=uploads
AWS_REGION=us-east-1

EMAIL_HOST=${EMAIL_HOST}
EMAIL_PORT=${EMAIL_PORT}
EMAIL_HOST_USER=${EMAIL_HOST_USER}
EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
EMAIL_USE_TLS=1
DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}

LISTEN_HTTP_PORT=8080
LISTEN_HTTPS_PORT=8443
BACKUP_RETENTION_DAYS=14
EOF

chmod 600 .env
info ".env written."

# ── Patch Caddyfile with domain ───────────────────────────────────────────────
sed -i.bak "s/admin@yourdomain.com/admin@${PLANE_DOMAIN}/g" caddy/Caddyfile
rm -f caddy/Caddyfile.bak
info "Caddyfile updated."

# ── Pull images ───────────────────────────────────────────────────────────────
info "Pulling Docker images (this may take a few minutes)..."
docker compose pull

# ── Start infrastructure first, run migrations, then start all ───────────────
info "Starting infrastructure services..."
docker compose up -d plane-db plane-redis plane-minio plane-rabbitmq

info "Waiting for PostgreSQL to be healthy..."
until docker compose exec plane-db pg_isready -U plane -d plane &>/dev/null; do
  sleep 2
done

info "Running database migrations..."
docker compose run --rm plane-migrator

info "Starting all services..."
docker compose up -d

info "────────────────────────────────────────────────"
info "Plane is starting up."
info "  URL: https://${PLANE_DOMAIN}"
info "  Allow 60-90 seconds for full startup."
info "  First user to register becomes the instance admin."
info "────────────────────────────────────────────────"
